### PR TITLE
Release the GIL for blocking sysctl syscalls

### PR DESCRIPTION
**Pull request by freqlabs**
Getting and setting sysctl values can potentially block in the kernel.
Release the GIL so other Python threads may progress while we wait.

### CODE REVIEW

**Comment by freqlabs** [comment]
I want to do a bit more testing with this on head, but the PR is here to let you know what's in the works.

**Comment by freqlabs** [comment]
Ok that last commit fixes the issue I have been hunting down on head. Ready for review.

**Review by william-gr — COMMENTED** [review]
Are we not releasing the GIL on some sysctl calls because its not expected to ever block because it doesn't get the value?

**Comment by freqlabs** [comment]
Right, I originally had released the GIL around every sysctl call but it felt like overkill so I ripped most of it back out. Most of the operations only take a read-many lock on the sysctl tree in the kernel and few things would block it by holding a writer lock. It would mainly be sysctl tree modifications (adding/removing nodes, such as when a pool is created or destroyed or when devices appear/disappear).

In the end, I erred on the side of not adding the overhead of releasing/taking the GIL in the common case. It would be pretty rare for an operation to block waiting for the sysctl tree lock, and when it does, the wait should be bounded by the size of the tree.

**Review by william-gr — APPROVED** [review]

**Pull request merged**
